plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'java-library'
}

dependencies {
    compileOnly project(':client-api')
    compileOnly('jakarta.enterprise:jakarta.enterprise.cdi-api')
    compileOnly('com.nimbusds:nimbus-jose-jwt')
    compileOnly 'jakarta.servlet:jakarta.servlet-api'

    implementation 'org.slf4j:slf4j-api'
}
