plugins {
    id 'war'
}

dependencies {
//    compileOnly('jakarta.annotation:jakarta.annotation-api')
//    compileOnly 'jakarta.servlet:jakarta.servlet-api'
//    compileOnly('jakarta.enterprise:jakarta.enterprise.cdi-api')
//    compileOnly 'jakarta.security.enterprise:jakarta.security.enterprise-api'

    compileOnly(project(':mat-auth-api'))

    runtimeOnly(project(':initializer-weblogic'))

    compileOnly project(':example:shared')
}
