matrikkel.oauth.discovery.url = http://localhost:8080/auth/realms/matrikkelen/.well-known/openid-configuration
matrikkel.oauth.client.id = matrikkelserver
matrikkel.oauth.client.secret = 8e78daf4-f447-4b0e-a373-edac67e60057
matrikkel.ouath.azp = matrikkelserver,matrikkelklient
